apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: trainnn
  annotations:
    "kubeshare/gpu_request": "0.5" # required if allocating GPU
    "kubeshare/gpu_limit": "1.0" # required if allocating GPU
    "kubeshare/gpu_mem": "1073741824" # required if allocating GPU # 1Gi, in bytes
    #"kubeshare/sched_affinity": "red" # optional
    #"kubeshare/sched_anti-affinity": "green" # optional
    #"kubeshare/sched_exclusion": "blue" # optional
spec: # PodSpec
  containers:
  - name: demo
    image: pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime
    env:
    - name: MODEL_HUB
      value: "pytorch/vision"
    - name: MODEL_NAME
      value: "resnet50"
    - name: TRAIN_SET
      value: "/workspace/pytorch_datasets/train/"
    - name: VAL_SET
      value: "/workspace/pytorch_datasets/val/"
    - name: TEST_SET
      value: "/workspace/pytorch_datasets/test/"
    - name: BATCH_SIZE
      value: "32"
    - name: TRACE_FOLDER
      value: "/workspace/pytorch_datasets/traces/"
    - name: EPOCHS
      value: "1"
    - name: LOSS_RATE
      value: "0.001"
    - name: CUDA_VISIBLE_DEVICES
      value: "-1"
    #command: ["nvidia-smi", "-L"]
    #command: ["python", "/workspace/Talos/pytorch-analyzer/resnet/trainNN.py"]
    command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
    resources:
      limits:
        cpu: "2"
        memory: "1Gi"
    volumeMounts:
    - mountPath: /workspace
      name: code-data
  volumes:
    name: code-data
    hostPath:
      path: /root/github
      type: Directory